# Generated by Django 2.1.2 on 2018-11-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('datamanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
