# Generated by Django 2.1.5 on 2019-02-23 07:07

import django.contrib.postgres.fields.jsonb
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datamanager', '0002_auto_20190120_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='MlModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('ds_in_cols', django.contrib.postgres.fields.jsonb.JSONField()),
                ('ds_out_cols', django.contrib.postgres.fields.jsonb.JSONField()),
                ('model', models.CharField(max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamanager.Dataset')),
            ],
        ),
    ]
