# Generated by Django 2.1.5 on 2019-02-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('datamanager', '0003_mlmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
