# Generated by Django 2.1.5 on 2019-03-16 02:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('datamanager', '0004_mlmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='degree',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
