# Generated by Django 2.1.5 on 2019-03-16 04:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('datamanager', '0005_mlmodel_degree'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataset',
            options={'verbose_name': 'Набор данных', 'verbose_name_plural': 'Наборы данных'},
        ),
        migrations.AlterModelOptions(
            name='mlmodel',
            options={'verbose_name': 'Модель', 'verbose_name_plural': 'Модели'},
        ),
    ]
