# Generated by Django 2.1.5 on 2019-04-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('datamanager', '0006_auto_20190316_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='activation',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='hidden_layer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
