# Generated by Django 2.1.5 on 2019-04-13 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datamanager', '0007_auto_20190413_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_values_threshold', models.FloatField(default=5)),
                ('p_value', models.FloatField(default=0.05)),
                ('nn_hidden_min', models.IntegerField(default=2)),
                ('nn_hidden_max', models.IntegerField(default=10)),
                ('poly_min', models.IntegerField(default=2)),
                ('poly_max', models.IntegerField(default=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Конфигурация',
                'verbose_name_plural': 'Конфигурации',
            },
        ),
    ]
