# Generated by Django 2.1.5 on 2019-04-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('datamanager', '0008_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='unique_values_threshold',
            field=models.IntegerField(default=5),
        ),
    ]
