# Generated by Django 2.1.5 on 2019-04-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('datamanager', '0009_auto_20190413_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='highlightLimit',
            field=models.IntegerField(default=5),
        ),
    ]
