# Generated by Django 2.1.5 on 2019-05-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('datamanager', '0010_configuration_highlightlimit'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='estimators',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
